import { StyleSheet } from 'react-native';


export default styles = StyleSheet.create({
    profileImage: {
        width: 32,
        height: 32,
        borderRadius: 50,
        marginLeft: 10,
        marginRight: 5,
        // marginVertical: 8,
        // marginBottom: 4,
    },
    lightCommentContainer: {
        width: '100%',
        backgroundColor: '#FFFFFF',
        borderColor: "#EBEBEB",
        // borderWidth: 1,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        marginTop: 8,
        borderRadius: 12.5,
    },
    darkCommentContainer: {
        width: '100%',
        backgroundColor: '#151515',
        borderColor: "#202020",
        // borderWidth: 1,
        borderTopWidth: 1,
        borderBottomWidth: 1,
        borderLeftWidth: 0.5,
        borderRightWidth: 0.5,
        marginTop: 8,
        borderRadius: 12.5,
    },
    lightUsername: {
        fontSize: 14,
        fontWeight: "600",
        color: '#5D5D5D',
        textAlign: "left",
    },
    darkUsername: {
        fontSize: 14,
        fontWeight: "600",
        color: '#DADADA',
        textAlign: "left",
    },
    lightCommentText: {
        fontSize: 18,
        fontWeight: "400",
        color: '#222222',
        textAlign: 'auto',
        marginHorizontal: 10,
        marginTop: 7,
        // marginBottom: 6,
    },
    darkCommentText: {
        fontSize: 18,
        fontWeight: "400",
        color: '#F4F4F4',
        textAlign: 'auto',
        marginHorizontal: 10,
        marginTop: 8,
        // marginBottom: 6,
    },
    lightViewText: {
        fontSize: 13,
        fontWeight: "500",
        color: '#1D1D1D',
        marginRight: 2,
    },
    darkViewText: {
        fontSize: 13,
        fontWeight: "500",
        color: '#E6E6E6',
        marginRight: 2,
    },
    lightBottomText: {
        fontSize: 13,
        fontWeight: "500",
        color: '#555555',
        marginRight: 10,
    },
    darkBottomText: {
        fontSize: 13,
        fontWeight: "500",
        color: '#DDDDDD',
        marginRight: 10,
    },
    overlayText: {
        fontSize: 22,
        fontWeight: "500",
        color: '#000000',
        alignSelf: 'center',
        marginHorizontal: 10,
    },
});